#!/bin/bash
# =========================================================================
#
# nexus-start
# Copyright 2008-2014 Gamegineer contributors and others.
# All rights reserved.
#
# This is a sample Nexus environment start script required for a
# Linux-based Gamegineer build server.  You should download this file to
# your build server and customize the variable definitions between the
# BEGIN-CUSTOM-VARIABLES and END-CUSTOM-VARIABLES markers.  The customized
# file should then be archived on your server and be part of your server's
# startup process.
#
# =========================================================================

# -------------------------------------------------------------------------
#
# BEGIN-CUSTOM-VARIABLES
#

#
# The build scripts home directory.  This is where your customized build
# scripts are located.
#
BUILD_SCRIPTS_HOME=~/scripts

#
# END-CUSTOM-VARIABLES
#
# -------------------------------------------------------------------------

#
# Start Nexus.
#
source $BUILD_SCRIPTS_HOME/nexus-environment.sh
nexus start
